<a href="https://colab.research.google.com/github/shajathmsc/Advanced-Python-Programming-Lab-Programs/blob/main/02_matrix_operations_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition:")
print(A + B)

print("\nSubtraction:")
print(A - B)

print("\nMultiplication:")
print(A * B)

print("\nMatrix Multiplication:")
print(np.dot(A, B))

print("\nTranspose of A:")
print(A.T)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[ 5 12]
 [21 32]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]
